######################################################################
# Automatically generated by qmake (2.01a) mié may 25 22:25:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += opstrama.h transceptor.h ventana.h
FORMS += ventana.ui
SOURCES += main.cpp opstrama.cpp transceptor.cpp ventana.cpp
RESOURCES += imagenes.qrc
